[tool.poetry]
name = "coding-playground"
version = "0.1.0"
description = ""
authors = ["ninochang <nino.chang@swag.live>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
